config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :create, :new, :show] do
    resources :reviews, only: [:new, :create, :index]
  end
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# resources :restaurants

# Rails.application.routes.draw do

#   get "reviews/:id", to: "reviews#show", as: :review

#   resources :restaurants do
#     resources :reviews, only: [:new, :create]
#     collection do
#       get "top", to: "restaurants#top"
#     end

#     member do
#       get "chef", to: "restaurants#chef"
#     end
#   end
#   # GET /restaurants/top
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
has_many :reviews, dependent: :destroy
validates :name, presence: true
validates :address, presence: true
validates :category, inclusion: { in: ["chinese","italian","japanese","french","belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, numericality: true,presence: true, inclusion: { in: (0..5)}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else render :new
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_reviews_path
    else render :new
    end
  end

    def index
      @restaurant = Restaurant.find(params[:restaurant_id])
      @reviews= @restaurant.reviews
    end

    private

    def review_params
      params.require(:review).permit(:content, :rating, :restaurant)
    end

  # def find_restaurant
  #    @restaurant = Restaurant.find(params[:id])
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h3> List of all restaurants </h3>
<ul>
<%@restaurants.each do |restaurant|%>
<li><%= restaurant.name %>  <%= link_to "GO", restaurant_path(restaurant) %> </li>
<%end%>
</ul>

<%= link_to "Create new Restau", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1> Create a new restaurant  </h1>

<%= form_for(@restaurant) do |f| %>

  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :address %>
  <%= f.text_field :address %>
  <br />

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <br />

  <%= f.label :category %>
  <%= f.text_field :category %>
  <br />

  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %> </h1>
<p> <%= @restaurant.address %> </p>
<p> <%= @restaurant.phone_number %> </p>
<p> <%= @restaurant.category %> </p>

<%= link_to "See Reviews", restaurant_reviews_path(@restaurant) %>
<br />
<%= link_to "back to restaurants", restaurants_path %>

app/views/reviews/index.html.erb
<h1><%= @restaurant.name %> </h1>
<% @reviews.each do |review| %>
<p><b>ils ont dit:</b> <%= review.content %> </p>
<p> note : <%= review.rating %> </p>
<br />
<% end %>
<br />
<%= link_to "New rating", new_restaurant_review_path %>
<br />
<%= link_to "back to restaurants", restaurants_path %>

app/views/reviews/new.html.erb
<h1>New review </h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>

  <%= f.submit "add a review" %>
<% end %>